version: "3.9"
services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
  migrations:
    build:
      context: .
      dockerfile : migrations.dockerfile
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: always
