apiVersion: batch/v1
kind: Job
metadata:
  name: orders-service-migrations
  namespace: orders-service
  labels:
    app: orders-service
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: orders-service-migrations
        image: 876701361933.dkr.ecr.eu-west-1.amazonaws.com/coffeemesh-orders-migrations:1.3
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: db-credentials
      restartPolicy: Never
